version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8001:8001"
    volumes:
      - ./backend/data:/app/data
      - ./backend/images:/app/images
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build: ./fronted
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8001
    depends_on:
      - backend
    restart: always
